import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { Card } from "../src/components/Home/Card";
import { data } from "../data";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>my todo app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-4xl mt-2 text-center"> Todo apps </h1>
      <ul className="flex ml-28 gap-x-10 text-2xl">
        <li className=" hover:border-gray-500 border-b ">
          <Link href="/addLinks">
            <a> Add Links</a>
          </Link>
        </li>
        <li className=" hover:border-gray-500 border-b ">
          <Link href="/links">
            <a> My Links</a>
          </Link>
        </li>
      </ul>

      <div className="grid grid-cols-4 m-10 p-10">
        {data.map((link) => (
          <Card key={link.id} link={link} />
        ))}
      </div>
    </div>
  );
}
